<?php
$arr = array(
    'assets_button' => __('OptimizePress: Add Element',OP_SN),

    'slide_2_title' => __('Choose the %element_name% Style',OP_SN),
    'slide_3_title' => __('Step 3 - %element_name%',OP_SN),
    'slide_4_title' => __('Step 4 - %element_name%',OP_SN),

    'help_video' => __('Help Video',OP_SN),

    //generic
    'add_new' => __('Add New',OP_SN),
    'add_new_field' => __('Add New Field',OP_SN),
    'add_new_row' => __('Add New Row',OP_SN),
    'advanced_options' => __('Advanced Options',OP_SN),
    'next_step' => __('Next Step',OP_SN),
    'after' => __('After',OP_SN),
    'alert_text' => __('Alert Message',OP_SN),
    'alignment' => __('Alignment',OP_SN),
    'alt_text' => __('Alt Text',OP_SN),
    'before' => __('Before',OP_SN),
    'bg_img' => __('Background Image',OP_SN),
    'bg_color' => __('Background Colour',OP_SN),
    'bg_color_start' => __('Background Gradient Start Colour',OP_SN),
    'bg_color_end' => __('Background Gradient End Colour (If left blank, color will be solid)',OP_SN),
    'border_style' => __('Border Style',OP_SN),
    'button_text' => __('Button Text',OP_SN),
    'center' => __('Center',OP_SN),
    'caption' => __('Caption',OP_SN),
    'color' => __('Colour',OP_SN),
    'columns' => __('Columns',OP_SN),
    'columns_count' => __('Number Of Columns',OP_SN),
    'company' => __('Company',OP_SN),
    'content' => __('Content',OP_SN),
    'dark' => __('Dark',OP_SN),
    'delete' => __('Delete',OP_SN),
    'dimensions' => __('Dimensions',OP_SN),
    'edit_element' => __('Edit Element',OP_SN),
    'edit_parent_element' => __('Edit Parent Element',OP_SN),
    'email_address' => __('Email Address',OP_SN),
    'feature_title' => __('Feature Title',OP_SN),
    'font_settings' => __('Custom Font Settings',OP_SN),
    'form_html' => __('Form HTML',OP_SN),
    'full_width' => __('Full Width',OP_SN),
    'GET' => __('GET',OP_SN),
    'header' => __('Header',OP_SN),
    'headline' => __('Headline',OP_SN),
    'height' => __('Height (px)',OP_SN),
    'highlight' => __('Highlight',OP_SN),
    'icon' => __('Icon (click on image to see all available icons)',OP_SN),
    'image' => __('Image',OP_SN),
    'information' => __('Information',OP_SN),
    'Insert' => __('Insert',OP_SN),
    'language' => __('Language',OP_SN),
    'large' => __('Large',OP_SN),
    'large_icon' => __('Large Icon',OP_SN),
    'large_image' => __('Large Image',OP_SN),
    'left' => __('Left',OP_SN),
    'letter_spacing' => __('Letter Spacing',OP_SN),
    'light' => __('Light',OP_SN),
    'like' => __('Like',OP_SN),
    'line_height' => __('Line Height',OP_SN),
    'link_title' => __('Link Title',OP_SN),
    'link_title_default' => __('Click here for popup',OP_SN),
    'link_url' => __('Link URL',OP_SN),
    'linkedin_language' => __('LinkedIn Language',OP_SN),
    'linkedin_url' => __('LinkedIn URL',OP_SN),
    'list_items' => __('List Items',OP_SN),
    'margin_top' => __('Top Margin (px)',OP_SN),
    'margin_bottom' => __('Bottom Margin (px)',OP_SN),
    'margin_left' => __('Left Margin (px)',OP_SN),
    'margin_right' => __('Right Margin (px)',OP_SN),
    'medium' => __('Medium',OP_SN),
    'most_popular' => __('Most Popular',OP_SN),
    'most_popular_text' => __('Most Popular Text',OP_SN),
    'move' => __('Move',OP_SN),
    'normal' => __('Normal',OP_SN),
    'slow' => __('Slow', OP_SN),
    'fast' => __('Fast', OP_SN),
    'none' => __('None', OP_SN),
    'fade' => __('Fade', OP_SN),
    'elastic' => __('Elastic', OP_SN),
    'zoomIn' => __('Zoom In', OP_SN),
    'zoomOut' => __('Zoom Out', OP_SN),
    'order_button_text' => __('Order Button Text',OP_SN),
    'order_button_url' => __('Order Button URL',OP_SN),
    'package_description' => __('Package Description',OP_SN),
    'package_features' => __('Package Features',OP_SN),
    'percentage' => __('Percentage',OP_SN),
    'placeholder' => __('Placeholder',OP_SN),
    'placeholder_image' => __('Placeholder Image',OP_SN),
    'placeholder_width' => __('Placeholder Width',OP_SN),
    'placeholder_height' => __('Placeholder Height',OP_SN),
    'POST' => __('POST',OP_SN),
    'posts_num' => __('Number Of Posts',OP_SN),
    'progress_text_shown' => __('Text Shown Next to Progress Percentage',OP_SN),
    'price' => __('Price',OP_SN),
    'pricing_unit' => __('Pricing Unit',OP_SN),
    'pricing_variable' => __('Pricing Variable',OP_SN),
    'privacy_notice' => __('Privacy Notice',OP_SN),
    'recommend' => __('Recommend',OP_SN),
    'remove_file' => __('Remove File',OP_SN),
    'remove_image' => __('Remove Image',OP_SN),
    'remove_row' => __('Remove Row',OP_SN),
    'reset' => __('Reset',OP_SN),
    'right' => __('Right',OP_SN),
    'rounded' => __('Rounded',OP_SN),
    'size' => __('Size',OP_SN),
    'small' => __('Small',OP_SN),
    'small_icon' => __('Small Icon',OP_SN),
    'step' => __('Step',OP_SN),
    'steps' => __('Steps',OP_SN),
    'style' => __('Style',OP_SN),
    'submit_button' => __('Submit Button',OP_SN),
    'text' => __('Text',OP_SN),
    'timer' => __('Timer (milliseconds)',OP_SN),
    'title' => __('Title',OP_SN),
    'Top' => __('Top',OP_SN),
    'type' => __('Type',OP_SN),
    'view_file' => __('View File',OP_SN),
    'video_type' => __('Video Type',OP_SN),
    'width' => __('Width (px)',OP_SN),
    'only_advanced_fields_available_when_editing' => __('There are no title options for the choosen style', OP_SN),
    'order' => __('Order', OP_SN),
    'required' => __('Required', OP_SN),
    'email_order' => __('Email field order', OP_SN),
    'name_order' => __('Name field order', OP_SN),
    'name_required' => __('Name required', OP_SN),

    'top_margin' => __('Top Margin (px)',OP_SN),
    'bottom_margin' => __('Bottom Margin (px)',OP_SN),
    'left_margin' => __('Left Margin (px)',OP_SN),
    'right_margin' => __('Right Margin (px)',OP_SN),

    'top_padding' => __('Top Padding (px)',OP_SN),
    'bottom_padding' => __('Bottom Padding (px)',OP_SN),
    'left_padding' => __('Left Padding (px)',OP_SN),
    'right_padding' => __('Right Padding (px)',OP_SN),

    'saved' => __('Saved', OP_SN),


    //colors
    'black' => __('Black',OP_SN),
    'blue' => __('Blue',OP_SN),
    'bright_green' => __('Bright Green',OP_SN),
    'dark_blue' => __('Dark Blue',OP_SN),
    'dark_grey' => __('Dark Grey',OP_SN),
    'dark_orange' => __('Dark Orange',OP_SN),
    'green' => __('Green',OP_SN),
    'light_blue' => __('Light Blue',OP_SN),
    'light_green' => __('Light Green',OP_SN),
    'light_orange' => __('Light Orange',OP_SN),
    'light_red' => __('Light Red',OP_SN),
    'light_violet' => __('Light Violet',OP_SN),
    'orange' => __('Orange',OP_SN),
    'pink' => __('Pink',OP_SN),
    'red' => __('Red',OP_SN),
    'silver' => __('Silver',OP_SN),
    'teal' => __('Teal',OP_SN),
    'violet' => __('Violet',OP_SN),
    'yellow' => __('Yellow',OP_SN),


    //tag specific
    //Affiliate Page Asset
    'affiliate_link' => __('Affiliate Link',OP_SN),

    //Bullet Block Asset
    'bullet_block_advanced1' => __('Customize specific styling options for your bullets.',OP_SN),
    'bullet_font_settings' => __('Bullet Styling',OP_SN),
    'bullet_upload_icon' => __('Upload bullet block icon (if custom icon is uploaded, the above icon will be ignored.)', OP_SN),

    //Content Toggle Asset
    'content_toggle_label' => __('Show Text',OP_SN),
    'content_toggle_hide_label' => __('Hide Text',OP_SN),
    'content_toggle_advanced1' => __('Customize specific styling options for your content toggle text',OP_SN),
    'content_toggle_font_settings' => __('Main Content Styling',OP_SN),

    //Calendar Date and Time Asset
    'calendar_bar_color' => __('Month Background Color', OP_SN),
    'day' => __('Day', OP_SN),
    'full_date' => __('Full Date', OP_SN),
    'month' => __('Month', OP_SN),
    'time_1' => __('Time 1', OP_SN),
    'time_2' => __('Time 2', OP_SN),
    'time_3' => __('Time 3', OP_SN),
    'timezone_1' => __('Timezone 1', OP_SN),
    'timezone_2' => __('Timezone 2', OP_SN),
    'timezone_3' => __('Timezone 3', OP_SN),

    //Countdown Cookie Timer Asset
    'countdown_cookie_timer_instructions' => __('Choose a length of time to count down to',OP_SN),
    'length_of_time' => __('Length of Time',OP_SN),
    'length_of_time_suffix' => __('Length of Time Suffix',OP_SN),

    //Countdown Timer Asset
    'countdown_timer_instructions' => __('Please enter the date in GMT time format. You can learn more about converting the time at http://www.greenwichmeantime.com.',OP_SN),
    'countdown_timer_advanced_instructions' => __('Use the below form to change the text that is associated with the years, months, days, hours, minutes and seconds on your countdown timer.',OP_SN),
    'years_text' => __('Years Text (Plural)',OP_SN),
    'years_text_singular' => __('Years Text (Singular)',OP_SN),
    'months_text' => __('Months Text {Plural)',OP_SN),
    'months_text_singular' => __('Months Text {Singular)',OP_SN),
    'days_text' => __('Days Text (Plural)',OP_SN),
    'days_text_singular' => __('Days Text (Singular)',OP_SN),
    'hours_text' => __('Hours Text (Plural)',OP_SN),
    'hours_text_singular' => __('Hours Text (Singular)',OP_SN),
    'minutes_text' => __('Minutes Text (Plural)',OP_SN),
    'minutes_text_singular' => __('Minutes Text (Singular)',OP_SN),
    'seconds_text' => __('Seconds Text (Plural)',OP_SN),
    'seconds_text_singular' => __('Seconds Text (Singular)',OP_SN),

    //Course Description Asset
    'course_description_step_2' => __('You may choose either an icon from the list below or upload one of your own', OP_SN),
    'course_description_title' => __('Training/Course Title', OP_SN),
    'course_description_content' => __('Training/Course Description', OP_SN),
    'course_description_advanced1' => __('Customize specific styling options for your course description text',OP_SN),
    'course_description_title_styling' => __('Course Description Title Styling',OP_SN),
    'course_description_content_styling' => __('Course Description Content Styling',OP_SN),

    //Feature Block Asset
    'feature_block_advanced1' => __('Customize specific styling options for your feature block text',OP_SN),
    'feature_block_title_styling' => __('Feature Block Title Styling',OP_SN),
    'feature_block_content_styling' => __('Feature Block Content Styling',OP_SN),
    'feature_block_link' => __('Link (if you use this option links from content area above will not be displayed)',OP_SN),
    'feature_upload_icon' => __('Upload featue block icon (if custom icon is uploaded, the above icon will be ignored.', OP_SN),

    //Feature Box Asset
    'feature_box_advanced1' => __('Customize specific styling options for your feature box text',OP_SN),
    'feature_box_title_styling' => __('Feature Box Title Styling',OP_SN),
    'feature_box_content_styling' => __('Feature Box Content Styling',OP_SN),
    'feature_text' => __('Feature Text',OP_SN),

    //Guarantee Box Asset
    'guarantee_box_advanced1' => __('Customize specific styling options for your guarantee box',OP_SN),
    'guarantee_box_title_styling' => __('Guarantee Box Title Styling',OP_SN),
    'guarantee_box_content_styling' => __('Guarantee Box Content Styling',OP_SN),

    'credit_card_icons' => __('Credit Card Icons',OP_SN),

    'divider_top_text' => __('Top Link Text',OP_SN),

    'tabs_count' => __('Number of tabs',OP_SN),
    'tabs' => __('Tabs',OP_SN),
    'tab' => __('Tab',OP_SN),

    'embed' => __('Embed Code',OP_SN),
    'video_embed_microcopy' => __('If you need to embed Wistia or EVS code, please use Custom HTML/Shortcode element and paste embed code there!',OP_SN),
    'URL' => __('URL',OP_SN),
    'hide_controls' => __('Hide Controls',OP_SN),
    'auto_play' => __('Auto Play',OP_SN),
    'auto_buffer' => __('Auto Buffering',OP_SN),
    'auto_buffer_help' => __('Enabling auto buffering will allow the video to be loaded before the user clicks play',OP_SN),
    'remove_youtube_logo' => __('Hide YouTube logo in control bar (will still show in corner of video on hover)', OP_SN),
    'show_title_bar' => __('Show title bar', OP_SN),
    'force_hd_mode' => __('Force HD mode', OP_SN),


    'title_alt' => __('Title Alt Attribute',OP_SN),
    'header_alt' => __('Header Alt Attribute',OP_SN),

    'tour_get_started_link' => __('Get Started URL',OP_SN),
    'tour_get_started_text' => __('Get Started Text',OP_SN),
    'tour_tour_link' => __('Tour Link URL',OP_SN),
    'tour_tour_text' => __('Tour Link Text',OP_SN),
    'tour_headline' => __('Headline',OP_SN),
    'tour_subheadline' => __('Sub Headline',OP_SN),


    'qna_questions' => __('Questions',OP_SN),
    'qna_question' => __('Question',OP_SN),
    'qna_answer' => __('Answer',OP_SN),
    'qna_qa_text' => __('Q &amp; A Text',OP_SN),
    'qna_large_q' => __('Large Q',OP_SN),


    'email_default' => __('Email Default Value',OP_SN),
    'name_default' => __('Name Default Value',OP_SN),
    'name' => __('Name',OP_SN),
    'email' => __('Email',OP_SN),
    'email_data' => __('Email Data',OP_SN),
    'new_window' => __('Open In New Window',OP_SN),
    'disable_name' => __('Disable Name',OP_SN),
    'method' => __('Method',OP_SN),
    'form_url' => __('Form URL',OP_SN),
    'redirect_url' => __('Redirect URL',OP_SN),
    'field_name' => __('Field Name',OP_SN),
    'extra_fields' => __('Extra Fields',OP_SN),


    'order_selected_step' => __('Selected Step',OP_SN),
    'order_step1_text' => __('Step 1 Text',OP_SN),
    'order_step1_href' => __('Step 1 Link URL',OP_SN),
    'order_step2_text' => __('Step 2 Text',OP_SN),
    'order_step2_href' => __('Step 2 Link URL',OP_SN),
    'order_step3_text' => __('Step 3 Text',OP_SN),

    'testimonial' => __('Testimonial',OP_SN),

    'width_help_add_suffix' => __('Please enter your width including your measurement unit e.g. \'px\' or \'%\'',OP_SN),

    'facebook_hide_like' => __('Hide Like button',OP_SN),
    'facebook_hide_like_help' => __('Hide the Facebook Like button above the comments',OP_SN),
    'facebook_language_help' => __('Set the language for your Facebook comments system here',OP_SN),
    'facebook_posts_number' => __('Number of posts to show',OP_SN),
    'facebook_posts_number_help' => __('Enter the number of Facebook comments to show by default_attr(we recommend 10)',OP_SN),
    'facebook_src_url' => __('Facebook Comments Source URL',OP_SN),
    'facebook_src_url_help' => __('If you would like to associate all your comments with a particular page on your site, or show the same comments on multiple pages (perhaps for a launch) enter the URL here. We recommend using your root domain URL.',OP_SN),

    'advanced_warning_2' => __('Warning: These options are for advanced users only.  Customizing these options can result in your elements looking distorted or your design breaking.  If in doubt, leave these options on their default settings.',OP_SN),

    'image_alignment' => __('Image Alignment',OP_SN),

    'main_text' => __('Main Text',OP_SN),

    'navigation_font_settings' => __('Navigation Content Styling',OP_SN),
    'navigation_advanced1' => __('Customize specific styling options for your navigation menu.',OP_SN),

    'order_box_advanced1' => __('Customize specific styling options for your order box',OP_SN),
    'width_needed_for_alignment_to_work' => __('For alignment to work you need to define width',OP_SN),

    'optin_box_advanced1' => __('Customize specific styling options for your optin box text',OP_SN),
    'optin_box_font_settings' => __('Optin Box Font Styling',OP_SN),

    'tabs_font_settings' => __('Tab Content Styling',OP_SN),
    'tabs_advanced1' => __('Customize specific styling options for your tab content',OP_SN),

    'testimonials_advanced1' => __('Customize specific styling options for your testimonial.',OP_SN),
    'testimonials_font_settings' => __('Testimonials Styling',OP_SN),

    'text_alignment' => __('Text Alignment',OP_SN),


    'text_block_content' => __('Use the WYSIWYG editor below to add content to your text block.',OP_SN),
    'text_block_font_settings' => __('Select the font size for your main body copy inside the text box. Please note this will not affect headline styles - use the overall',OP_SN),
    'text_block_top_padding' => __('Text Block Top Padding (px)',OP_SN),
    'text_block_bottom_padding' => __('Text Block Bottom Padding (px)',OP_SN),
    'text_block_left_padding' => __('Text Block Left Padding (px)',OP_SN),
    'text_block_right_padding' => __('Text Block Right Padding',OP_SN),
    'text_block_padding_help' => __('Adjust the padding of the inside of your text box (px)',OP_SN),
    'text_block_top_margin' => __('Text Block Top Margin (px)',OP_SN),
    'text_block_top_margin_help' => __('Adjust the margin above your text box (px)',OP_SN),
    'text_block_bottom_margin' => __('Text Block Bottom Margin (px)',OP_SN),
    'text_block_bottom_margin_help' => __('Adjust the margin below your text box (px)',OP_SN),
    'text_block_width' => __('Text Block Width (px)',OP_SN),

    'top_color' => __('Top Color',OP_SN),

    'date' => __('Date',OP_SN),
    'date_format' => __('Date Format',OP_SN),
    'date_format_microcopy' => __('Full list of available options can be found in the <a href="http://php.net/manual/en/function.date.php#refsect1-function.date-parameters" target="_blank">PHP documentation</a>, use a back slash (\) to escape special characters',OP_SN),

    'dynamic_delay_timer' => __('Enter the time when to show your content (in milliseconds)',OP_SN),

    'terms_text' => __('Terms &amp; Conditions Text',OP_SN),
    'accept_text' => __('Accept checkbox label',OP_SN),
    'accept_text_default' => __('I understand and agree to all other Terms and Conditions detailed on this page.',OP_SN),

    'column_text' => __('Column Text',OP_SN),

    'light_or_dark' => __('Light or Dark',OP_SN),

    /* Social Sharing */
    'default_tweet_text' => __('Default Tweet Text',OP_SN),
    'facebook_settings' => __('Facebook Settings',OP_SN),
    'facebook_like_url' => __('URL to Like',OP_SN),
    'button_text' => __('Button Text',OP_SN),
    'twitter_count_url' => __('URL of the page to share',OP_SN),
    'twitter_name' => __('Twitter screen name (enter without "@" sign, if entered, will be added to Tweet as via @screen_name)',OP_SN),
    'twitter_settings' => __('Twitter Settings',OP_SN),
    'google_settings' => __('Google +1 Settings',OP_SN),
    'google_url' => __('URL to +1',OP_SN),
    'pinterest_settings' => __('Pinterest Settings',OP_SN),
    'pinterest_url' => __('URL of the page to pin',OP_SN),
    'pinterest_image_url' => __('URL of the image to pin',OP_SN),
    'pinterest_description' => __('Description of the page to be pinned',OP_SN),
    'share' => __('Share',OP_SN),
    'stumbleupon_settings' => __('StumbleUpon',OP_SN),
    'stumbleupon_url' => __('Page URL (Optional)',OP_SN),
    'linkedin_settings' => __('LinkedIn Settings',OP_SN),

    'navigation_menu' => __('Navigation Menu',OP_SN),
    'navigation_help' => __('Customize your navigation menu using the options below. If you have not yet created a navigation menu, go to <a href="nav-menus.php" target="_blank">Appearance &gt; Menus</a> to create your first menu',OP_SN),

    'payment_gateway' => __('Payment Gateway', OP_SN),
    'membership_level' => __('Membership Level', OP_SN),
    'want_to_charge' => __('I want to charge', OP_SN),
    'one_time' => __('Pick one option', OP_SN),
    'description' => __('Description', OP_SN),
    'packages' => __('Packages'),
    'first' => __('I\'ll offer the first', OP_SN),
    'days' => __('Select:', OP_SN),
    'at' => __('@', OP_SN),
    'one_time_auth' => __('/', OP_SN),
    'one_time_cc' => __('/', OP_SN),
    'one_time' => __('/', OP_SN),
    'currency_cc' => __('Currency', OP_SN),
    'currency_new' => __('Currency', OP_SN),
    'page_style' => __('Paypal Page Style', OP_SN),
    'click_product_type' => __('ClickBank product type', OP_SN),
    'click_product_item' => __('ClickBank product item #', OP_SN),
    'click_skin' => __('ClickBank custom form skin', OP_SN),
    'click_skin_note' => __('Note: Enter custom form skin code to brand your shopping cart', OP_SN),
    'click_fid' => __('PitchPlus Upsell Flow ID', OP_SN),
    'click_fid_note' => __("Note: Optional ClickBank PitchPlus Upsell Flow ID, which MUST correlate with a PitchPlus Upsell Flow you've configured at ClickBank.com.", OP_SN),
    'click_ur' => __('PitchPlus Upsell Flow action', OP_SN),
    'click_ur_note' => __('Note: Optional ClickBank PitchPlus Upsell Flow action (a accept or d decline), which MUST correlate with instructions provided by ClickBank.com for PitchPlus Upsell Flows.', OP_SN),
    'click_f' => __('PitchPlus Upsell Flow session ID', OP_SN),
    'click_f_note' => __('Note: Optional ClickBank PitchPlus Upsell Flow session ID, which MUST correlate with instructions provided by ClickBank.com for PitchPlus Upsell Flows.', OP_SN),
    'one_time_clickbank' => __('Fixed term access', OP_SN),
    'click_trial_period' => __('ClickBank trial period', OP_SN),
    'click_rebill' => __(', then ReBill', OP_SN),

    // Button designer
    'subtext' => __('Subtext', OP_SN),
    'font_properties' => __('Font properties', OP_SN),
    'text_shadow' => __('Text Shadow', OP_SN),
    'vertical_axis' => __('Vertical Axis', OP_SN),
    'horizontal_axis' => __('Horizontal Axis', OP_SN),
    'styling' => __('Styling', OP_SN),
    'border_size' => __('Border Size', OP_SN),
    'border_radius' => __('Border Radius', OP_SN),
    'border_color' => __('Border Color', OP_SN),
    'border_opacity' => __('Border Opacity', OP_SN),
    'border_weight' => __('Border Thickness/Weight', OP_SN),
    'gradient' => __('Gradient', OP_SN),
    'shine' => __('Shine', OP_SN),
    'drop_shadow' => __('Drop Shadow', OP_SN),
    'spread_radius' => __('Spread Radius', OP_SN),
    'shadow_color' => __('Shadow Color', OP_SN),
    'opacity' => __('Opacity', OP_SN),
    'inner_shadow' => __('Inner Shadow', OP_SN),
    'blur_radius' => __('Blur Radius', OP_SN),
    'save_preset' => __('Save Preset', OP_SN),
    'delete_preset' => __('Delete Preset', OP_SN),
    'letter_spacing' => __('Letter Spacing', OP_SN),

    //Membership order button
    'no_options_for_this_slide' => __('Default Payment Gateway button will be used. No options for customization', OP_SN),

    //Membership sidebars
    'membership_sidebar_product' => __('Product', OP_SN),
    'membership_sidebar_category' => __('Category', OP_SN),
    'membership_sidebar_subcategory' => __('Subcategory', OP_SN),
    'membership_sidebar_show_children' => __('List pages from page parent product', OP_SN),
    'membership_sidebar_same_level' => __('Show pages from this page level only', OP_SN),
    'membership_sidebar_title_styling' => __('Title styling', OP_SN),
    'membership_sidebar_content_styling' => __('Content styling', OP_SN),

    // Javascript element
    'javascript_content' => __('Enter custom JavaScript (Please ensure you do not include any calls to external jQuery libraries as this may break your page!)', OP_SN),
    'javascript_description' => __('WARNING: Be careful when entering JavaScript to your page. It should be valid, or it will break your page.', OP_SN),


    // Membership page listing element
    'membership_page_listings_columns' => __('Number of columns', OP_SN),
    'show_comments' => __('Show comments', OP_SN),
    'show_drip_content' => __('Show drip delay timer (Content will only show for this option if you do not have hide protected content activated)', OP_SN),
    'page_listings_content_styling' => __('Page listings content styling', OP_SN),
    'page_listings_title_styling' => __('Page listings title styling', OP_SN),
    'page_listings_resize_thumb_height' => __('Resize thumbnail height? (Use this option if you are using icons for your thumbnails - ensure all icons are the same height)', OP_SN),
    'page_listings_show_children' => __('Show Page Children only - this will list any pages directly under this page in your page heirarchy.', OP_SN),
    'page_listings_sort_order' => __('Order pages', OP_SN),
    'hide_description' => __('Hide description', OP_SN),

    //Membership login form
    'public_title' => __('Public title', OP_SN),
    'when_not_logged_in' => __('(when not logged in)', OP_SN),
    'redirection_after_login' => __('Redirection after login', OP_SN),
    'signup_now' => __('Signup now', OP_SN),
    'enter_url_or_use_automatic' => __('(enter URL, or just use <code>%%automatic%%</code>, leave blank to exclude this link)', OP_SN),
    'additional_xhtml_php_code' => __('Additional XHTML/PHP code?', OP_SN),
    'profile_title' => __('Profile title', OP_SN),
    'when_logged_in' => __('(when logged in)', OP_SN),
    'display_gravatar_image' => __('Display gravatar image?', OP_SN),
    'link_to_gravatar' => __('Link to gravatar.com?', OP_SN),
    'display_user_name' => __("Display user's name?", OP_SN),
    'my_account' => __('My account', OP_SN),
    'edit_profile' => __('Edit profile', OP_SN),
    'redirection_after_logout' => __('Redirection after logout', OP_SN),
    'login_welcome_page' => __('Login welcome page', OP_SN),
    'login_screen' => __('Login screen', OP_SN),
    'previous_page' => __('Previous page', OP_SN),
    'home_page' => __('Home page', OP_SN),
    'yes_display_gravatar' => __('Yes, display Gravatar', OP_SN),
    'no_do_not_display' => __('No, do NOT display', OP_SN),
    'no_do_not_apply' => __('No, do NOT apply', OP_SN),
    'yes_apply_link' => __('Yes, apply link', OP_SN),
    'yes_display_user_name' => __("Yes, display User's name", OP_SN),

    // Optin box
    'integration_type' => __('Integration Type', OP_SN),
    'provider_list' => __('Provider List', OP_SN),
    'thank_you_page_url' => __('Thank You Page URL', OP_SN),
    'text_below_button' => __('Textual Link Below Button', OP_SN),
    'gotowebinar' => __('GoToWebinar', OP_SN),
    'gotowebinar_list' => __('GoToWebinar Webinar', OP_SN),
    'ems_loading_time' => __('Note: Lists can take up to 1 minute to be retrieved from your provider', OP_SN),
    'double_optin' => __('Double Optin', OP_SN),
    'no_extra_fields_for_selected_style' => __('This Optin Box design does not support additional fields', OP_SN),

    // Images Asset
    'asset_images_custom_width' => __('Custom Image Width?',OP_SN),

    // Languages
    'english' => __('English', OP_SN),
    'french' => __('French', OP_SN),
    'spanish' => __('Spanish', OP_SN),
    'russian' => __('Russian', OP_SN),
    'german' => __('German', OP_SN),
    'italian' => __('Italian', OP_SN),
    'portugese' => __('Portugese', OP_SN),
    'romanian' => __('Romanian', OP_SN),
    'turkish' => __('Turkish', OP_SN),
    'japanese' => __('Japanese', OP_SN),
    'indonesian' => __('Indonesian', OP_SN),
    'malay' => __('Malay', OP_SN),
    'korean' => __('Korean', OP_SN),
    'swedish' => __('Swedish', OP_SN),
    'czech' => __('Czech', OP_SN),
    'dutch' => __('Dutch', OP_SN),
    'polish' => __('Polish', OP_SN),
    'norwegian' => __('Norwegian', OP_SN),
    'danish' => __('Danish', OP_SN),

    // Live Search
    'live_search_product' => __('Product', OP_SN),
    'live_search_category' => __('Category', OP_SN),
    'live_search_subcategory' => __('Subcategory', OP_SN),
    'live_search_all_pages' => __('Search within all pages', OP_SN),
    'live_search_placeholder' => __('Search box text', OP_SN),

    // file download
    'select_level' => __('Membership level', OP_SN),
    'select_packages' => __('Membership packages', OP_SN),
    'file_name' => __('File name', OP_SN),
    'file_description' => __('File description', OP_SN),
    'file' => __('File', OP_SN),


    // custom_html
    'custom_html_description' => __('WARNING: Be careful when adding custom HTML. It should be valid HTML or it could break your page.', OP_SN),

    // membership order button
    'currency' => __('Currency', OP_SN),
    'success_url' => __('Success URL', OP_SN),

    // Popup / OverlayOptimizer
    'popup_width' => __("Window width (px). <br />If you enter 0 or leave this field empty, OverlayOptimizer window will be sized according to it's content size."),
    'popup_button' => __('OverlayOptimizer button', OP_SN),
    'popup_container' => __('OverlayOptimizer window', OP_SN),
    'open_effect' => __('Open effect', OP_SN),
    'close_effect' => __('Close effect', OP_SN),
    'open_speed' => __('Open speed', OP_SN),
    'close_speed' => __('Close speed', OP_SN),
);